image: docker:latest

services:
  - docker:dind
  - name: registry.conci.info/conci/image/couchbase:master
    alias: couchbase
    script:
      - couchbase-cli bucket-create -c localhost:8091 -u conci -p devpass \
                   --bucket=test-bucket \
                   --bucket-type=couchbase \
                   --bucket-port=11222 \
                   --bucket-ramsize=200 \
                   --bucket-replica=1 \
                   --wait

stages:
  - test

test phpunit:
  stage: test
  image: registry.conci.info/conci/image/fpm:master
  script:
    - composer install --no-suggest --no-progress
    - php -dzend_extension=xdebug.so ./vendor/bin/phpunit --coverage-text --colors=never

