image: docker:latest

services:
- name: registry.conci.info/conci/image/couchbase:master
  alias: couchbase

stages:
  - test

test phpunit:
  stage: test
  image: registry.conci.info/conci/image/base:master
  script:
    - php ./tests/create-bucket.php
    - composer install --no-suggest --no-progress
    - php -dzend_extension=xdebug.so ./vendor/bin/phpunit --coverage-text --colors=never

