image: docker:latest

services:
  - docker:dind
  - registry.conci.info/conci/image/couchbase:master

stages:
  - test

test phpunit:
  stage: test
  image: registry.conci.info/conci/image/base:master
  script:
    - yum install wget
    - wget http://packages.couchbase.com/releases/couchbase-release/couchbase-release-1.0-2-x86_64.rpm
    - rpm -iv couchbase-release-1.0-2-x86_64.rpm
    - yum install libcouchbase-devel gcc gcc-c++ php-devel zlib-devel
    - pecl install couchbas
    - composer install --no-suggest --no-progress
    - php -dzend_extension=xdebug.so ./vendor/bin/phpunit --coverage-text --colors=never