image: docker:latest

services:
  - docker:dind
  - name: registry.conci.info/conci/image/couchbase:master
    alias: couchbase

stages:
  - test

test phpunit:
  stage: test
  image: registry.conci.info/conci/image/fpm:master
  script:
    - ping couchbase
    - composer install --no-suggest --no-progress
    - php -dzend_extension=xdebug.so ./vendor/bin/phpunit --coverage-text --colors=never

