image: docker:latest

services:
  - docker:dind
  - couchbase

stages:
  - test

test phpunit:
  stage: test
  image: registry.conci.info/jobsy/backend/main:${CI_COMMIT_REF_NAME}
  script:
    - composer install --no-suggest --no-progress
    - php -dzend_extension=xdebug.so ./vendor/bin/phpunit --coverage-text --colors=never


couchbase:
  image: registry.conci.info/conci/image/couchbase